// <auto-generated />
namespace MySmartApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migratiom26_09_13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migratiom26_09_13));
        
        string IMigrationMetadata.Id
        {
            get { return "201909261603519_Migratiom26_09_13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
